fix: added testnet attack registry address
 During “Step 5 — Open for Attack” of BattleChain QuickStart for Manual (Foundry) you are expected to check the contract state by running `just check-state` that runs the following command.

```
cast call $ATTACK_REGISTRY "getAgreementState(address)(uint8)" $AGREEMENT_ADDRESS \
        --rpc-url https://testnet.battlechain.com
```

It causes the following error.

```
sh: ATTACK_REGISTRY: unbound variable
error: Recipe `check-state` failed on line 61 with exit code 127
```

`just check-state` expects `ATTACK_REGISTRY` address to be saved in `.env`. However, the Quickstart fails to mention `ATTACK_REGISTRY` address (0xdD029a6374095EEb4c47a2364Ce1D0f47f007350) anywhere during the process or in the .env.example file.

This PR fixes this issue by adding the `ATTACK_REGISTRY` address in the .env.example file.